### PR TITLE
Update 3rdparty dependencies

### PR DESCRIPTION
**Pull request by marcoambrosini**
ref https://github.com/nextcloud-gmbh/server/issues/685

### CODE REVIEW

**Comment by marcoambrosini** [comment]
@nickvergessen do you know what's wrong with ci?

**Review by JuliaKirschenheuter — APPROVED** [review]

**Comment by nickvergessen** [comment]
You need to commit compiled js.

**Comment by marcoambrosini** [comment]
looks good now @nickvergessen ?

**Pull request merged**
