### PR TITLE
Add SPDX header

### PR DESCRIPTION
**Pull request by AndyScherzinger**

### CODE REVIEW

**Review by DorraJaouad — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
@blizzz @Altahrim @skjnldsv see change below. I would like to test-drive this in 29.0.**1** to ensure this works fine with the checksum / file-list stuff on packaging well, when running a Nextcloud, to not run into issues with the updater (which we saw happening with adding the dependency lock files back in September last year).

So I would only ask merging the v29 backport upon your feedback.

**Comment by AndyScherzinger** [comment]
Thanks a lot for the review and approval @DorraJaouad - highly appreciated 💯

**Pull request merged**
